from enum import Enum


class Voice(Enum):
    ANTON_SAMOKHVALOV_GPU = 'anton_samokhvalov.gpu' 
    SHITOVA_GPU = 'shitova.gpu' 
    OKSANA_GPU = 'oksana.gpu' 
    KOLYA_GPU = 'kolya.gpu' 
    KOSTYA_GPU = 'kostya.gpu' 
    KROSH_GPU = 'krosh.gpu' 
    NASTYA_GPU = 'nastya.gpu' 
    SASHA_GPU = 'sasha.gpu' 
    TATYANA_ABRAMOVA_GPU = 'tatyana_abramova.gpu' 
    VALTZ_GPU = 'valtz.gpu' 
    ERMIL_GPU = 'ermil.gpu' 
    JANE_GPU = 'jane.gpu' 
    OMAZH_GPU = 'omazh.gpu' 
    ZAHAR_GPU = 'zahar.gpu'
    ALYSS = 'alyss'
    ANTON_SAMOKHVALOV = 'anton_samokhvalov'
    SHITOVA = 'shitova'
    ERKANYAVAS = 'erkanyavas'
    FAIRY_TALES = 'fairy_tales'
    OKSANA = 'oksana'
    KOLYA = 'kolya'
    KOSTYA = 'kostya'
    KROSH = 'krosh'
    LEVITAN = 'levitan'
    NASTYA = 'nastya'
    NICK = 'nick'
    SASHA = 'sasha'
    SILAERKAN = 'silaerkan'
    TANYA = 'tanya'
    TATYANA_ABRAMOVA = 'tatyana_abramova'
    VALTZ = 'valtz'
    ZHENYA = 'zhenya'
    ERMIL = 'ermil'
    JANE = 'jane'
    OMAZH = 'omazh'
    ZAHAR = 'zahar'


